### PR TITLE
Function can be assigned to variable.

### PR DESCRIPTION
**Pull request by nmdis1999**
Added `assignment.ukiyo` to test if function can be assigned to a variable.

### CODE REVIEW

**Comment by ptersilie** [comment]
Has this already been implemented? Or does it just work out of the box? Let's try.

bors try

**Comment by ptersilie** [comment]
Oh, I see. Sorry there's been a misunderstanding. What we meant is assigning the function **definition** to a variable. Look again closely at the examples I gave you, e.g.
```
fn foo() {
    let f = fn (a, b) {
        return a * b;
    }
    let x = f();
    print(x);
}
```
See that a function is defined inside another function and stored inside a variable. That variable can then be called. It's also possible to pass around the variable to other functions and called later, e.g.:
```
fn foo() {
    let f = fn (a, b) {
        return a * b;
    }
    return f;
}

fn main() {
    let x = foo()();
    print(x);
}
```

**Comment by nmdis1999** [comment]
Yeah, I saw it as two parts:
1. Function call can be assigned to a variable.
2. Function definition can be assigned to a variable. 

This change is to verify the first part only. I am working on the second :)

**Comment by ptersilie** [comment]
Oh, my bad. Let's merge this in first then.

bors r+

**Pull request merged**
